baseURL = "https://jinasanami.github.io/"
languageCode = "ja-jp"
title = "麻浪迅のホームページ"
theme = "profile"
enableRobotsTXT = true
timeZone = "Asia/Tokyo"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[pagination]
pagerSize = 3

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
name = "BIO"
weight = 1
url = "/bio/"

[[menu.main]]
name = "MUSIC"
weight = 2
url = "/music/"

[[menu.main]]
name = "WORKS"
weight = 3
url = "/works/"

[[menu.main]]
name = "SAMPLE"
weight = 4
url = "/sample/"

[[menu.main]]
name = "EVENT"
weight = 5
url = "/event/"

[[menu.main]]
name = "BLOG"
weight = 6
url = "/blog/"

[[menu.main]]
name = "LINK"
weight = 7
url = "/link/"

[[menu.main]]
name = "CONTACT"
weight = 8
url = "/contact/"

[params]
author = "Jin Asanami"
description = "音楽家・麻浪迅の公式サイト。新時代のJ-Jazzシーンを切り開くのは、このあたしだ！"
favicon = "/img/logo.png"
colorScheme = "auto"
hideColorSchemeToggle = true
dateFormat = "2006-01-02"
since = 2022
copyright = "Jin Asanami"
buildFuture = true

[params.hero]
enable = false
#intro = ""
title = "Jin Asanami"
#subtitle = ""
content = "麻浪迅のホームページにようこそ！"
image = "/img/logo.png"

[params.hero.bottomImage]
enable = false

[[params.hero.socialLinks.customIcons]]
icon = "/img/logo/mi.webp"
url = "https://prismisskey.space/@jinasanami"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-bandcamp"
url = "https://jinasanami.bandcamp.com"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-soundcloud"
url = "https://soundcloud.com/hayatehay"

[[params.hero.socialLinks.customIcons]]
icon = "/img/logo/skeb.png"
url = "https://skeb.jp/@hayatehay"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/hayatehay"

[params.navbar.menus]
disableAbout = true
disableNews = false
disableExperience = true
disableEducation = true
disableProjects = true
disableAchievements = true
disableContact = true

[params.about]
enable = true
title = "ABOUT ME"
image = "/img/jinasanami.png"
content = """
<h3>麻浪 迅 (あさなみ・じん)</h3>

2005年2月1日生まれ。生まれも育ちも長野県。

同人サークル「中村音楽工業」の第1号ミュージシャンで、音楽作品もそこから発売される。2024年、EP「月影」でCDデビュー。

既存のジャンルに囚われない自由な発想で、新時代のJ-Jazzシーンを切り開く。その一方でゲーム制作やOS開発、Vtuber活動(休止中)など、その手が伸びる先は数知れず。
"""

[params.news]
enable = true
index = false
title = "NEWS"

[[params.news.items]]
title = "オムニバスアルバム「We Love Otoskey!」に楽曲を提供"
date = "2026/02/01"
content = """
Tanukeyサーバー「おとすきー」にてナカムラミュージックレコーズ（現・[日本ルリタニアレコード](https://ruritania.jp/tags/日本ルリタニアレコード)）のアカウントを運営していた御縁で、サービス終了記念のオムニバスアルバム「We Love Otoskey!」に参加します。

曲名：Blue Light Star

5月発売予定の3rd EPからの先行公開です。無料でダウンロードできますので、是非どうぞ。
"""

[[params.news.items]]
title = "コミックマーケット107参加と3rd SP「幻聴インヴィテーション」発売決定"
date = "2025/11/07"
content = """
12月31日、東京ビッグサイト 南ホール1階 b-41aで待ってるよ！

それに合わせて、3rd SP「幻聴インヴィテーション」を発売します。
- [ミュージックカード](/music/nrmh-4)

※ミュージックカードのご利用方法は、[こちらのページ](/musiccard/)をご覧下さい。

なお、一般販売はイベント終了後の予定です。
"""

[[params.news.items]]
title = "2nd EP「Exsultatio」発売決定"
date = "2025/8/23"
content = """
9月26日発売予定。商品詳細はこちら
- [ミュージックカード](/music/nrmh-3)
- [CDエクストラ](/music/nrch-3)
- [DSDディスク](/music/nrgh-2)

※ミュージックカードのご利用方法は、[こちらのページ](/musiccard/)をご覧下さい。

なお、Bandcampでは9月5日、その他のサイトでは9月26日にダウンロード販売を開始する予定です。
"""

[[params.news.items]]
title = "DLsiteで一部タイトルの配信開始"
date = "2025/03/05"
content = """
ダウンロード販売サイト「DLsite」で、一部作品の配信を始めました。

- [月影 (1349990)](https://www.dlsite.com/home/announce/=/product_id/RJ01349990.html)
- [朝焼け -second track- (1350035)](https://www.dlsite.com/home/announce/=/product_id/RJ01350035.html)
- [Alma/哀流 (1350054)](https://www.dlsite.com/home/announce/=/product_id/RJ01350054.html)
"""

[[params.news.items]]
title = "2nd SP「Alma/哀流」発売"
date = "2025/03/05"
content = """
3月5日発売。商品詳細はこちら
- [CDエクストラ](/music/nrch-2)
- [ミュージックカード](/music/nrmh-2)

※ミュージックカードのご利用方法は、[こちらのページ](/musiccard/)をご覧下さい。

なお、同時にダウンロード販売も開始しました。
"""

[[params.news.items]]
title = "1st SP「朝焼け -second track-」ミュージックカード発売"
date = "2025/01/10"
content = """
[商品詳細はこちら](/music/nrmh-1)

※ご利用方法は、[こちらのページ](/musiccard/)をご覧下さい。

"""

[[params.news.items]]
title = "Bandcamp配信開始"
date = "2025/01/10"
content = """
音楽配信プラットフォーム「Bandcamp」にて、「月影」「朝焼け -second track-」「DEMO 2024 DEC」の配信が始まりました！

[Jin Asanami/麻浪迅 - Bandcamp](https://jinasanami.bandcamp.com/)
"""

[[params.news.items]]
title = "Skeb開設"
date = "2024/11/07"
content = """
コミッションサービス「Skeb」にアカウントを作りました！ご依頼お待ちしております…。

[@hayatehay - Skeb](https://skeb.jp/@hayatehay)
"""

[[params.news.items]]
title = "「月影」MP3無料ダウンロードのご案内"
date = "2024/10/05"
content = """
販促のため、MP3ファイルをサウンドクラウドに公開しました→~~https://soundcloud.com/hayatehay/moonlight~~公開終了しました

ダウンロードの際は「More」→「Download File」を選んで下さい。

対象楽曲
- 月影 (EP「月影」収録)
"""

[[params.news.items]]
title = "1st EP「月影」の発売日が決定"
date = "2024/06/30"
content = """2024年7月7日の予定です。みんな買ってね！んで友達にも勧めてね！予約は7月1日から受け付け中。

[販売ページ(NMI MUSIC STORE/BOOTH)](https://nmimusic.booth.pm/items/5865685)
"""

[[params.news.items]]
title = "ホームページとブログを統合"
date = "2024/03/25"
content = """
いい加減利便性が悪いので統合しました。

テーマはこれを使っています。本当にありがとう。

[Hugo Profile by @gurusabarish](https://github.com/gurusabarish/hugo-profile)
"""

[[params.news.items]]
title = "ホームページの移転を開始"
date = "2023/11/24"
content = """
アットウィキからの移転を開始しました。これから色々なコンテンツを公開していくので楽しみに待っててね。
"""

[params.listPages]
disableFeaturedImage = false

[params.singlePages]
socialShare = true

[params.singlePages.readTime]
enable = false
content = "min read"

[params.singlePages.scrollprogress]
enable = true

[params.singlePages.tags]
openInNewTab = true

  [params.terms]
  read = "読む"
  toc = "目次"
  copyright = "All rights reserved"
  pageNotFound = "ページが見つかりません"
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"

